<?php require __DIR__ . '/partials/header.php'; ?>
<main>
    <section class="website-public-hero website-classic-hero"><div><h1><?= e($sections['hero_title'] ?? 'Welcome to Our School') ?></h1><p><?= e($sections['hero_subtitle'] ?? '') ?></p><a href="<?= e($sections['hero_button_link'] ?? '/login') ?>"><?= e($sections['hero_button_text'] ?? 'Learn More') ?></a></div><?php if (!empty($sections['hero_image'])): ?><img src="<?= e(public_upload_url($sections['hero_image'])) ?>" alt="School"><?php else: ?><div class="website-public-image-fallback">School Life</div><?php endif; ?></section>
    <section class="website-classic-stats"><span><strong>25+</strong>Teachers</span><span><strong>500+</strong>Students</span><span><strong>3</strong>Terms</span><span><strong>100%</strong>Focus</span></section>
    <section class="website-public-page website-classic-about"><div><?php if (!empty($sections['about_image'])): ?><img src="<?= e(public_upload_url($sections['about_image'])) ?>" alt="About school"><?php else: ?><div class="website-public-image-fallback">About Our School</div><?php endif; ?></div><article><h2><?= e($sections['about_title'] ?? 'About Our School') ?></h2><p><?= nl2br(e($sections['about_content'] ?? 'Please update this section from the Website Manager.')) ?></p></article></section>
    <section class="website-public-section"><h2><?= e($sections['why_choose_title'] ?? 'Why Choose Us') ?></h2><div class="website-public-card-grid website-classic-card-grid"><?php foreach (array_filter(preg_split('/\r\n|\r|\n/', $sections['why_choose_points'] ?? '')) as $point): ?><article><?= e($point) ?></article><?php endforeach; ?></div></section>
    <section class="website-public-section website-classic-programs"><h2><?= e($sections['programs_title'] ?? 'Our Programs') ?></h2><p><?= nl2br(e($sections['programs_content'] ?? '')) ?></p></section>
    <section class="website-public-section"><h2><?= e($sections['gallery_title'] ?? 'Students Gallery') ?></h2><div class="website-public-gallery website-classic-gallery"><?php foreach ($gallery as $item): ?><img src="<?= e(public_upload_url($item['image_path'])) ?>" alt="<?= e($item['title']) ?>"><?php endforeach; ?><?php if (empty($gallery)): ?><p>No gallery images have been uploaded yet.</p><?php endif; ?></div></section>
    <section class="website-public-section website-review-classic"><h2>Parent Reviews</h2><div class="website-review-grid"><?php foreach ($reviews as $review): ?><article><?php if (!empty($review['parent_image'])): ?><img src="<?= e(public_upload_url($review['parent_image'])) ?>" alt="<?= e($review['parent_name']) ?>"><?php else: ?><span class="website-review-avatar"><?= e(strtoupper(substr($review['parent_name'], 0, 2))) ?></span><?php endif; ?><div class="website-review-stars"><?= str_repeat('★', (int) $review['rating']) ?></div><p><?= e($review['review_text']) ?></p><strong><?= e($review['parent_name']) ?></strong><small><?= e($review['parent_title']) ?></small></article><?php endforeach; ?><?php if (empty($reviews)): ?><p>Parent reviews will appear here soon.</p><?php endif; ?></div></section>
    <section class="website-classic-cta"><h2><?= e($sections['contact_title'] ?? 'Contact Us') ?></h2><a href="/website/contact">Talk to Us</a></section>
</main>
<?php require __DIR__ . '/partials/footer.php'; ?>
